version: '3.9'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - elasticsearch

  admin:
    build: ./admin
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - api

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: search
      POSTGRES_PASSWORD: search
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  pgdata:
