apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search-admin.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "search-admin.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "search-admin.name" . }}
    spec:
      containers:
        - name: admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: search-admin-env
