apiVersion: v1
kind: Service
metadata:
  name: {{ include "search-admin.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ include "search-admin.name" . }}
