apiVersion: v1
kind: Secret
metadata:
  name: search-api-env
stringData:
  SHOPIFY_API_KEY: "{{ .Values.env.SHOPIFY_API_KEY }}"
  SHOPIFY_API_SECRET: "{{ .Values.env.SHOPIFY_API_SECRET }}"
  DATABASE_URL: "{{ .Values.env.DATABASE_URL }}"
  REDIS_URL: "{{ .Values.env.REDIS_URL }}"
  ELASTICSEARCH_HOST: "{{ .Values.env.ELASTICSEARCH_HOST }}"
